export const FEATCH_PHONES_START = 'FEATCH_PHONES_START'
export const FEATCH_PHONES_SUCCESS = 'FEATCH_PHONES_SUCCESS'
export const FEATCH_PHONES_FAILURE = 'FEATCH_PHONES_FAILURE'

export const LOAD_MORE_PHONES_START = 'LOAD_MORE_PHONES_START'
export const LOAD_MORE_PHONES_SUCCESS = 'LOAD_MORE_PHONES_SUCCESS'
export const LOAD_MORE_PHONES_FAILURE = 'LOAD_MORE_PHONES_FAILURE'

export const FEATCH_PHONE_BY_ID_START = 'FEATCH_PHONE_BY_ID_START'
export const FEATCH_PHONE_BY_ID_SUCCESS = 'FEATCH_PHONE_BY_ID_SUCCESS'
export const FEATCH_PHONE_BY_ID_FAILURE = 'FEATCH_PHONE_BY_ID_FAILURE'

export const SEARCH_PHONE = 'SEARCH_PHONE'
export const EDIT_NAME = 'EDIT_NAME'
