export const LOAD_MORE_ITEMS_START = 'LOAD_MORE_ITEMS_START'
export const LOAD_MORE_ITEMS_SUCCESS = 'LOAD_MORE_ITEMS_SUCCESS'
export const LOAD_MORE_ITEMS_FAILURE = 'LOAD_MORE_ITEMS_FAILURE'

export const FEATCH_ITEM_BY_ID_START = 'FEATCH_ITEM_BY_ID_START'
export const FEATCH_ITEM_BY_ID_SUCCESS = 'FEATCH_ITEM_BY_ID_SUCCESS'
export const FEATCH_ITEM_BY_ID_FAILURE = 'FEATCH_ITEM_BY_ID_FAILURE'

export const SEARCH_ITEM = 'SEARCH_ITEM'
export const EDIT_NAME = 'EDIT_NAME'
export const CHANGE_PAGE = 'CHANGE_PAGE'